### ISSUE TITLE
The ansible-selvpc-modules does not work on the new version ansible

### ISSUE THREAD

**Issue by IgorOhrimenko** [selectel/ansible-selvpc-modules#4]
Hello. 

> ansible-selvpc-modules 1.2.2 has requirement ansible>=2.6.18

Ubuntu 20.04
ansible 2.9.8 > 2.6.18
Python 3.8.2

ansible-playbook ansible-selvpc-modules/examples/example.yaml -vvv

`The full traceback is:
Traceback (most recent call last):
  File "/home/igorohrimenko/.ansible/tmp/ansible-tmp-1589450913.0975344-8405-12940898879231/AnsiballZ_selvpc_projects.py", line 102, in <module>
    _ansiballz_main()
  File "/home/igorohrimenko/.ansible/tmp/ansible-tmp-1589450913.0975344-8405-12940898879231/AnsiballZ_selvpc_projects.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/igorohrimenko/.ansible/tmp/ansible-tmp-1589450913.0975344-8405-12940898879231/AnsiballZ_selvpc_projects.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.selvpc.selvpc_projects', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_selvpc_projects_payload_le5xcdxm/ansible_selvpc_projects_payload.zip/ansible/modules/selvpc/selvpc_projects.py", line 23, in <module>
ImportError: cannot import name 'custom_user_agent' from 'ansible.modules.selvpc' (/tmp/ansible_selvpc_projects_payload_le5xcdxm/ansible_selvpc_projects_payload.zip/ansible/modules/selvpc/__init__.py)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/igorohrimenko/.ansible/tmp/ansible-tmp-1589450913.0975344-8405-12940898879231/AnsiballZ_selvpc_projects.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/igorohrimenko/.ansible/tmp/ansible-tmp-1589450913.0975344-8405-12940898879231/AnsiballZ_selvpc_projects.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/igorohrimenko/.ansible/tmp/ansible-tmp-1589450913.0975344-8405-12940898879231/AnsiballZ_selvpc_projects.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.selvpc.selvpc_projects', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_selvpc_projects_payload_le5xcdxm/ansible_selvpc_projects_payload.zip/ansible/modules/selvpc/selvpc_projects.py\", line 23, in <module>\nImportError: cannot import name 'custom_user_agent' from 'ansible.modules.selvpc' (/tmp/ansible_selvpc_projects_payload_le5xcdxm/ansible_selvpc_projects_payload.zip/ansible/modules/selvpc/__init__.py)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
`

**Comment by dstdfx** [comment]
Hi, thank you for the appeal but unfortunately the current version of ansible-selvpc-modules v1.2.x is compatible with ansible >= 2.7.16, < 2.7.0 only. 
We also suggest you to take a look at our official Terraform provider (https://github.com/terraform-providers/terraform-provider-selectel) if it fits your need.
